name: Test

on:
  [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: nexys-system/gh-actions-spa-test@v1.1.0
        with:
          nodeversion: 14
          build-command: yarn build
     
